/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RedemarrageRouteImport } from './routes/redemarrage'
import { Route as PostesRouteImport } from './routes/postes'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as EvaluationsRouteImport } from './routes/evaluations'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIndexRouteImport } from './routes/tests.index'
import { Route as RapportsIndexRouteImport } from './routes/rapports.index'
import { Route as EntretiensIndexRouteImport } from './routes/entretiens.index'
import { Route as ComportementIndexRouteImport } from './routes/comportement.index'
import { Route as CandidatsIndexRouteImport } from './routes/candidats.index'
import { Route as TestsIdRouteImport } from './routes/tests.$id'
import { Route as RapportsIdRouteImport } from './routes/rapports.$id'
import { Route as EntretiensIdRouteImport } from './routes/entretiens.$id'
import { Route as ComportementIdRouteImport } from './routes/comportement.$id'
import { Route as CandidatsIdRouteImport } from './routes/candidats.$id'

const RedemarrageRoute = RedemarrageRouteImport.update({
  id: '/redemarrage',
  path: '/redemarrage',
  getParentRoute: () => rootRouteImport,
} as any)
const PostesRoute = PostesRouteImport.update({
  id: '/postes',
  path: '/postes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationsRoute = EvaluationsRouteImport.update({
  id: '/evaluations',
  path: '/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIndexRoute = TestsIndexRouteImport.update({
  id: '/tests/',
  path: '/tests/',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsIndexRoute = RapportsIndexRouteImport.update({
  id: '/rapports/',
  path: '/rapports/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntretiensIndexRoute = EntretiensIndexRouteImport.update({
  id: '/entretiens/',
  path: '/entretiens/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComportementIndexRoute = ComportementIndexRouteImport.update({
  id: '/comportement/',
  path: '/comportement/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatsIndexRoute = CandidatsIndexRouteImport.update({
  id: '/candidats/',
  path: '/candidats/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIdRoute = TestsIdRouteImport.update({
  id: '/tests/$id',
  path: '/tests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsIdRoute = RapportsIdRouteImport.update({
  id: '/rapports/$id',
  path: '/rapports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntretiensIdRoute = EntretiensIdRouteImport.update({
  id: '/entretiens/$id',
  path: '/entretiens/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ComportementIdRoute = ComportementIdRouteImport.update({
  id: '/comportement/$id',
  path: '/comportement/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatsIdRoute = CandidatsIdRouteImport.update({
  id: '/candidats/$id',
  path: '/candidats/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/evaluations': typeof EvaluationsRoute
  '/machines': typeof MachinesRoute
  '/parametres': typeof ParametresRoute
  '/postes': typeof PostesRoute
  '/redemarrage': typeof RedemarrageRoute
  '/candidats/$id': typeof CandidatsIdRoute
  '/comportement/$id': typeof ComportementIdRoute
  '/entretiens/$id': typeof EntretiensIdRoute
  '/rapports/$id': typeof RapportsIdRoute
  '/tests/$id': typeof TestsIdRoute
  '/candidats/': typeof CandidatsIndexRoute
  '/comportement/': typeof ComportementIndexRoute
  '/entretiens/': typeof EntretiensIndexRoute
  '/rapports/': typeof RapportsIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/evaluations': typeof EvaluationsRoute
  '/machines': typeof MachinesRoute
  '/parametres': typeof ParametresRoute
  '/postes': typeof PostesRoute
  '/redemarrage': typeof RedemarrageRoute
  '/candidats/$id': typeof CandidatsIdRoute
  '/comportement/$id': typeof ComportementIdRoute
  '/entretiens/$id': typeof EntretiensIdRoute
  '/rapports/$id': typeof RapportsIdRoute
  '/tests/$id': typeof TestsIdRoute
  '/candidats': typeof CandidatsIndexRoute
  '/comportement': typeof ComportementIndexRoute
  '/entretiens': typeof EntretiensIndexRoute
  '/rapports': typeof RapportsIndexRoute
  '/tests': typeof TestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/evaluations': typeof EvaluationsRoute
  '/machines': typeof MachinesRoute
  '/parametres': typeof ParametresRoute
  '/postes': typeof PostesRoute
  '/redemarrage': typeof RedemarrageRoute
  '/candidats/$id': typeof CandidatsIdRoute
  '/comportement/$id': typeof ComportementIdRoute
  '/entretiens/$id': typeof EntretiensIdRoute
  '/rapports/$id': typeof RapportsIdRoute
  '/tests/$id': typeof TestsIdRoute
  '/candidats/': typeof CandidatsIndexRoute
  '/comportement/': typeof ComportementIndexRoute
  '/entretiens/': typeof EntretiensIndexRoute
  '/rapports/': typeof RapportsIndexRoute
  '/tests/': typeof TestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/evaluations'
    | '/machines'
    | '/parametres'
    | '/postes'
    | '/redemarrage'
    | '/candidats/$id'
    | '/comportement/$id'
    | '/entretiens/$id'
    | '/rapports/$id'
    | '/tests/$id'
    | '/candidats/'
    | '/comportement/'
    | '/entretiens/'
    | '/rapports/'
    | '/tests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/evaluations'
    | '/machines'
    | '/parametres'
    | '/postes'
    | '/redemarrage'
    | '/candidats/$id'
    | '/comportement/$id'
    | '/entretiens/$id'
    | '/rapports/$id'
    | '/tests/$id'
    | '/candidats'
    | '/comportement'
    | '/entretiens'
    | '/rapports'
    | '/tests'
  id:
    | '__root__'
    | '/'
    | '/evaluations'
    | '/machines'
    | '/parametres'
    | '/postes'
    | '/redemarrage'
    | '/candidats/$id'
    | '/comportement/$id'
    | '/entretiens/$id'
    | '/rapports/$id'
    | '/tests/$id'
    | '/candidats/'
    | '/comportement/'
    | '/entretiens/'
    | '/rapports/'
    | '/tests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EvaluationsRoute: typeof EvaluationsRoute
  MachinesRoute: typeof MachinesRoute
  ParametresRoute: typeof ParametresRoute
  PostesRoute: typeof PostesRoute
  RedemarrageRoute: typeof RedemarrageRoute
  CandidatsIdRoute: typeof CandidatsIdRoute
  ComportementIdRoute: typeof ComportementIdRoute
  EntretiensIdRoute: typeof EntretiensIdRoute
  RapportsIdRoute: typeof RapportsIdRoute
  TestsIdRoute: typeof TestsIdRoute
  CandidatsIndexRoute: typeof CandidatsIndexRoute
  ComportementIndexRoute: typeof ComportementIndexRoute
  EntretiensIndexRoute: typeof EntretiensIndexRoute
  RapportsIndexRoute: typeof RapportsIndexRoute
  TestsIndexRoute: typeof TestsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/redemarrage': {
      id: '/redemarrage'
      path: '/redemarrage'
      fullPath: '/redemarrage'
      preLoaderRoute: typeof RedemarrageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postes': {
      id: '/postes'
      path: '/postes'
      fullPath: '/postes'
      preLoaderRoute: typeof PostesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluations': {
      id: '/evaluations'
      path: '/evaluations'
      fullPath: '/evaluations'
      preLoaderRoute: typeof EvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/': {
      id: '/tests/'
      path: '/tests'
      fullPath: '/tests/'
      preLoaderRoute: typeof TestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports/': {
      id: '/rapports/'
      path: '/rapports'
      fullPath: '/rapports/'
      preLoaderRoute: typeof RapportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entretiens/': {
      id: '/entretiens/'
      path: '/entretiens'
      fullPath: '/entretiens/'
      preLoaderRoute: typeof EntretiensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comportement/': {
      id: '/comportement/'
      path: '/comportement'
      fullPath: '/comportement/'
      preLoaderRoute: typeof ComportementIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidats/': {
      id: '/candidats/'
      path: '/candidats'
      fullPath: '/candidats/'
      preLoaderRoute: typeof CandidatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$id': {
      id: '/tests/$id'
      path: '/tests/$id'
      fullPath: '/tests/$id'
      preLoaderRoute: typeof TestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports/$id': {
      id: '/rapports/$id'
      path: '/rapports/$id'
      fullPath: '/rapports/$id'
      preLoaderRoute: typeof RapportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entretiens/$id': {
      id: '/entretiens/$id'
      path: '/entretiens/$id'
      fullPath: '/entretiens/$id'
      preLoaderRoute: typeof EntretiensIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comportement/$id': {
      id: '/comportement/$id'
      path: '/comportement/$id'
      fullPath: '/comportement/$id'
      preLoaderRoute: typeof ComportementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidats/$id': {
      id: '/candidats/$id'
      path: '/candidats/$id'
      fullPath: '/candidats/$id'
      preLoaderRoute: typeof CandidatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EvaluationsRoute: EvaluationsRoute,
  MachinesRoute: MachinesRoute,
  ParametresRoute: ParametresRoute,
  PostesRoute: PostesRoute,
  RedemarrageRoute: RedemarrageRoute,
  CandidatsIdRoute: CandidatsIdRoute,
  ComportementIdRoute: ComportementIdRoute,
  EntretiensIdRoute: EntretiensIdRoute,
  RapportsIdRoute: RapportsIdRoute,
  TestsIdRoute: TestsIdRoute,
  CandidatsIndexRoute: CandidatsIndexRoute,
  ComportementIndexRoute: ComportementIndexRoute,
  EntretiensIndexRoute: EntretiensIndexRoute,
  RapportsIndexRoute: RapportsIndexRoute,
  TestsIndexRoute: TestsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
