/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestsRouteImport } from './routes/tests'
import { Route as RapportsRouteImport } from './routes/rapports'
import { Route as PostesRouteImport } from './routes/postes'
import { Route as ParametresRouteImport } from './routes/parametres'
import { Route as MachinesRouteImport } from './routes/machines'
import { Route as EntretiensRouteImport } from './routes/entretiens'
import { Route as ComportementRouteImport } from './routes/comportement'
import { Route as CandidatsRouteImport } from './routes/candidats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TestsIdRouteImport } from './routes/tests.$id'
import { Route as EntretiensIdRouteImport } from './routes/entretiens.$id'
import { Route as ComportementIdRouteImport } from './routes/comportement.$id'
import { Route as CandidatsIdRouteImport } from './routes/candidats.$id'

const TestsRoute = TestsRouteImport.update({
  id: '/tests',
  path: '/tests',
  getParentRoute: () => rootRouteImport,
} as any)
const RapportsRoute = RapportsRouteImport.update({
  id: '/rapports',
  path: '/rapports',
  getParentRoute: () => rootRouteImport,
} as any)
const PostesRoute = PostesRouteImport.update({
  id: '/postes',
  path: '/postes',
  getParentRoute: () => rootRouteImport,
} as any)
const ParametresRoute = ParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesRoute = MachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => rootRouteImport,
} as any)
const EntretiensRoute = EntretiensRouteImport.update({
  id: '/entretiens',
  path: '/entretiens',
  getParentRoute: () => rootRouteImport,
} as any)
const ComportementRoute = ComportementRouteImport.update({
  id: '/comportement',
  path: '/comportement',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatsRoute = CandidatsRouteImport.update({
  id: '/candidats',
  path: '/candidats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestsIdRoute = TestsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TestsRoute,
} as any)
const EntretiensIdRoute = EntretiensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EntretiensRoute,
} as any)
const ComportementIdRoute = ComportementIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ComportementRoute,
} as any)
const CandidatsIdRoute = CandidatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CandidatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidats': typeof CandidatsRouteWithChildren
  '/comportement': typeof ComportementRouteWithChildren
  '/entretiens': typeof EntretiensRouteWithChildren
  '/machines': typeof MachinesRoute
  '/parametres': typeof ParametresRoute
  '/postes': typeof PostesRoute
  '/rapports': typeof RapportsRoute
  '/tests': typeof TestsRouteWithChildren
  '/candidats/$id': typeof CandidatsIdRoute
  '/comportement/$id': typeof ComportementIdRoute
  '/entretiens/$id': typeof EntretiensIdRoute
  '/tests/$id': typeof TestsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidats': typeof CandidatsRouteWithChildren
  '/comportement': typeof ComportementRouteWithChildren
  '/entretiens': typeof EntretiensRouteWithChildren
  '/machines': typeof MachinesRoute
  '/parametres': typeof ParametresRoute
  '/postes': typeof PostesRoute
  '/rapports': typeof RapportsRoute
  '/tests': typeof TestsRouteWithChildren
  '/candidats/$id': typeof CandidatsIdRoute
  '/comportement/$id': typeof ComportementIdRoute
  '/entretiens/$id': typeof EntretiensIdRoute
  '/tests/$id': typeof TestsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidats': typeof CandidatsRouteWithChildren
  '/comportement': typeof ComportementRouteWithChildren
  '/entretiens': typeof EntretiensRouteWithChildren
  '/machines': typeof MachinesRoute
  '/parametres': typeof ParametresRoute
  '/postes': typeof PostesRoute
  '/rapports': typeof RapportsRoute
  '/tests': typeof TestsRouteWithChildren
  '/candidats/$id': typeof CandidatsIdRoute
  '/comportement/$id': typeof ComportementIdRoute
  '/entretiens/$id': typeof EntretiensIdRoute
  '/tests/$id': typeof TestsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidats'
    | '/comportement'
    | '/entretiens'
    | '/machines'
    | '/parametres'
    | '/postes'
    | '/rapports'
    | '/tests'
    | '/candidats/$id'
    | '/comportement/$id'
    | '/entretiens/$id'
    | '/tests/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidats'
    | '/comportement'
    | '/entretiens'
    | '/machines'
    | '/parametres'
    | '/postes'
    | '/rapports'
    | '/tests'
    | '/candidats/$id'
    | '/comportement/$id'
    | '/entretiens/$id'
    | '/tests/$id'
  id:
    | '__root__'
    | '/'
    | '/candidats'
    | '/comportement'
    | '/entretiens'
    | '/machines'
    | '/parametres'
    | '/postes'
    | '/rapports'
    | '/tests'
    | '/candidats/$id'
    | '/comportement/$id'
    | '/entretiens/$id'
    | '/tests/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidatsRoute: typeof CandidatsRouteWithChildren
  ComportementRoute: typeof ComportementRouteWithChildren
  EntretiensRoute: typeof EntretiensRouteWithChildren
  MachinesRoute: typeof MachinesRoute
  ParametresRoute: typeof ParametresRoute
  PostesRoute: typeof PostesRoute
  RapportsRoute: typeof RapportsRoute
  TestsRoute: typeof TestsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tests': {
      id: '/tests'
      path: '/tests'
      fullPath: '/tests'
      preLoaderRoute: typeof TestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapports': {
      id: '/rapports'
      path: '/rapports'
      fullPath: '/rapports'
      preLoaderRoute: typeof RapportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/postes': {
      id: '/postes'
      path: '/postes'
      fullPath: '/postes'
      preLoaderRoute: typeof PostesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parametres': {
      id: '/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof ParametresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines': {
      id: '/machines'
      path: '/machines'
      fullPath: '/machines'
      preLoaderRoute: typeof MachinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entretiens': {
      id: '/entretiens'
      path: '/entretiens'
      fullPath: '/entretiens'
      preLoaderRoute: typeof EntretiensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comportement': {
      id: '/comportement'
      path: '/comportement'
      fullPath: '/comportement'
      preLoaderRoute: typeof ComportementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidats': {
      id: '/candidats'
      path: '/candidats'
      fullPath: '/candidats'
      preLoaderRoute: typeof CandidatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tests/$id': {
      id: '/tests/$id'
      path: '/$id'
      fullPath: '/tests/$id'
      preLoaderRoute: typeof TestsIdRouteImport
      parentRoute: typeof TestsRoute
    }
    '/entretiens/$id': {
      id: '/entretiens/$id'
      path: '/$id'
      fullPath: '/entretiens/$id'
      preLoaderRoute: typeof EntretiensIdRouteImport
      parentRoute: typeof EntretiensRoute
    }
    '/comportement/$id': {
      id: '/comportement/$id'
      path: '/$id'
      fullPath: '/comportement/$id'
      preLoaderRoute: typeof ComportementIdRouteImport
      parentRoute: typeof ComportementRoute
    }
    '/candidats/$id': {
      id: '/candidats/$id'
      path: '/$id'
      fullPath: '/candidats/$id'
      preLoaderRoute: typeof CandidatsIdRouteImport
      parentRoute: typeof CandidatsRoute
    }
  }
}

interface CandidatsRouteChildren {
  CandidatsIdRoute: typeof CandidatsIdRoute
}

const CandidatsRouteChildren: CandidatsRouteChildren = {
  CandidatsIdRoute: CandidatsIdRoute,
}

const CandidatsRouteWithChildren = CandidatsRoute._addFileChildren(
  CandidatsRouteChildren,
)

interface ComportementRouteChildren {
  ComportementIdRoute: typeof ComportementIdRoute
}

const ComportementRouteChildren: ComportementRouteChildren = {
  ComportementIdRoute: ComportementIdRoute,
}

const ComportementRouteWithChildren = ComportementRoute._addFileChildren(
  ComportementRouteChildren,
)

interface EntretiensRouteChildren {
  EntretiensIdRoute: typeof EntretiensIdRoute
}

const EntretiensRouteChildren: EntretiensRouteChildren = {
  EntretiensIdRoute: EntretiensIdRoute,
}

const EntretiensRouteWithChildren = EntretiensRoute._addFileChildren(
  EntretiensRouteChildren,
)

interface TestsRouteChildren {
  TestsIdRoute: typeof TestsIdRoute
}

const TestsRouteChildren: TestsRouteChildren = {
  TestsIdRoute: TestsIdRoute,
}

const TestsRouteWithChildren = TestsRoute._addFileChildren(TestsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidatsRoute: CandidatsRouteWithChildren,
  ComportementRoute: ComportementRouteWithChildren,
  EntretiensRoute: EntretiensRouteWithChildren,
  MachinesRoute: MachinesRoute,
  ParametresRoute: ParametresRoute,
  PostesRoute: PostesRoute,
  RapportsRoute: RapportsRoute,
  TestsRoute: TestsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
